// <auto-generated />
using System;
using Margen.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Margen.Infrastructure.Migrations
{
    [DbContext(typeof(MargenDbContext))]
    [Migration("20260804035452_DosFechasDeCobro")]
    partial class DosFechasDeCobro
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Margen.Domain.Entities.AccessToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<DateTime?>("LastUsedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Scopes")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character(64)")
                        .IsFixedLength();

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("DeviceId", "RevokedAt");

                    b.ToTable("AccessTokens");
                });

            modelBuilder.Entity("Margen.Domain.Entities.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<long>("Balance")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("CreditLimit")
                        .HasColumnType("bigint");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character(3)")
                        .IsFixedLength();

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("LastFour")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("character(4)")
                        .IsFixedLength();

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.ToTable("Accounts", t =>
                        {
                            t.HasCheckConstraint("CK_Accounts_LastFour_Digits", "\"LastFour\" ~ '^[0-9]{4}$'");
                        });
                });

            modelBuilder.Entity("Margen.Domain.Entities.Alert", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DedupeKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Detail")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid?>("IncomingEmailId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsUrgent")
                        .HasColumnType("boolean");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<Guid?>("RecurringPaymentId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("TransactionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DedupeKey")
                        .IsUnique()
                        .HasFilter("\"ResolvedAt\" IS NULL");

                    b.HasIndex("IncomingEmailId");

                    b.HasIndex("RecurringPaymentId");

                    b.HasIndex("TransactionId");

                    b.HasIndex("ResolvedAt", "IsUrgent", "CreatedAt");

                    b.ToTable("Alerts");
                });

            modelBuilder.Entity("Margen.Domain.Entities.BudgetPeriod", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<long>("ActualIncome")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("ClosedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("CommittedSavings")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<long>("ExpectedIncome")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsClosed")
                        .HasColumnType("boolean");

                    b.PrimitiveCollection<int[]>("PayDays")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.Property<long>("SafetyFund")
                        .HasColumnType("bigint");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("StartDate")
                        .IsUnique();

                    b.ToTable("BudgetPeriods", t =>
                        {
                            t.HasCheckConstraint("CK_BudgetPeriods_Order", "\"EndDate\" >= \"StartDate\"");
                        });
                });

            modelBuilder.Entity("Margen.Domain.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Icon")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("Margen.Domain.Entities.CategoryBudget", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<long>("Adjustment")
                        .HasColumnType("bigint");

                    b.Property<long>("Allocated")
                        .HasColumnType("bigint");

                    b.Property<Guid>("BudgetPeriodId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("BudgetPeriodId", "CategoryId")
                        .IsUnique();

                    b.ToTable("CategoryBudgets");
                });

            modelBuilder.Entity("Margen.Domain.Entities.Device", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("PublicKeyFingerprint")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character(64)")
                        .IsFixedLength();

                    b.Property<string>("PublicKeySpki")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("PublicKeyFingerprint")
                        .IsUnique();

                    b.ToTable("Devices");
                });

            modelBuilder.Entity("Margen.Domain.Entities.DeviceChallenge", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ConsumedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nonce")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("Nonce")
                        .IsUnique();

                    b.ToTable("DeviceChallenges");
                });

            modelBuilder.Entity("Margen.Domain.Entities.IncomingEmail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("text");

                    b.Property<string>("BodyHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character(64)")
                        .IsFixedLength();

                    b.Property<string>("FailureReason")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime>("FetchedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MessageId")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)");

                    b.Property<string>("ParserName")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<int?>("ParserVersion")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ReceivedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Sender")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("BodyHash")
                        .IsUnique();

                    b.HasIndex("MessageId")
                        .IsUnique();

                    b.HasIndex("Status", "ReceivedAt");

                    b.ToTable("IncomingEmails");
                });

            modelBuilder.Entity("Margen.Domain.Entities.MerchantRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsUserDefined")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastAppliedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MatchKind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Pattern")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<long>("TimesApplied")
                        .HasColumnType("bigint");

                    b.Property<int>("Weight")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("IsActive", "Weight")
                        .IsDescending(false, true);

                    b.HasIndex("Pattern", "MatchKind")
                        .IsUnique();

                    b.ToTable("MerchantRules");
                });

            modelBuilder.Entity("Margen.Domain.Entities.RecurringPayment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<string>("Cadence")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DayOfCycle")
                        .HasColumnType("integer");

                    b.Property<long>("ExpectedAmount")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<DateOnly?>("LastPaidDate")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("NextDueDate")
                        .HasColumnType("date");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("IsActive", "NextDueDate");

                    b.ToTable("RecurringPayments", t =>
                        {
                            t.HasCheckConstraint("CK_RecurringPayments_DiaDelCiclo", "\"DayOfCycle\" BETWEEN 1 AND 31");

                            t.HasCheckConstraint("CK_RecurringPayments_MontoPositivo", "\"ExpectedAmount\" > 0");
                        });
                });

            modelBuilder.Entity("Margen.Domain.Entities.StatementProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<int?>("AmountColumn")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CreditColumn")
                        .HasColumnType("integer");

                    b.Property<int>("DateColumn")
                        .HasColumnType("integer");

                    b.Property<string>("DateFormat")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int?>("DebitColumn")
                        .HasColumnType("integer");

                    b.Property<string>("Decimals")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("Delimiter")
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)");

                    b.Property<int>("DescriptionColumn")
                        .HasColumnType("integer");

                    b.Property<bool>("InvertSign")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<int>("SkipRows")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("StatementProfiles", t =>
                        {
                            t.HasCheckConstraint("CK_StatementProfiles_TieneMonto", "\"AmountColumn\" IS NOT NULL OR \"DebitColumn\" IS NOT NULL OR \"CreditColumn\" IS NOT NULL");
                        });
                });

            modelBuilder.Entity("Margen.Domain.Entities.Transaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<long>("Amount")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("CategoryConfirmedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<string>("ClassificationSource")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("ConfidenceBasisPoints")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character(3)")
                        .IsFixedLength();

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid?>("DuplicateOfTransactionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Fingerprint")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid?>("IncomingEmailId")
                        .HasColumnType("uuid");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("MerchantNormalized")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("MerchantRaw")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("PostedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("RefundsTransactionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DuplicateOfTransactionId");

                    b.HasIndex("Fingerprint")
                        .IsUnique();

                    b.HasIndex("IncomingEmailId");

                    b.HasIndex("MerchantNormalized");

                    b.HasIndex("OccurredAt")
                        .IsDescending();

                    b.HasIndex("RefundsTransactionId");

                    b.HasIndex("Status");

                    b.HasIndex("AccountId", "OccurredAt");

                    b.HasIndex("CategoryId", "OccurredAt");

                    b.HasIndex("Direction", "OccurredAt");

                    b.HasIndex("MerchantNormalized", "CategoryId")
                        .HasFilter("\"CategoryConfirmedAt\" IS NOT NULL");

                    b.ToTable("Transactions", t =>
                        {
                            t.HasCheckConstraint("CK_Transactions_Amount_NoNegativo", "\"Amount\" >= 0");

                            t.HasCheckConstraint("CK_Transactions_Confidence_Rango", "\"ConfidenceBasisPoints\" BETWEEN 0 AND 10000");

                            t.HasCheckConstraint("CK_Transactions_SinAutoreferencia", "\"RefundsTransactionId\" IS DISTINCT FROM \"Id\" AND \"DuplicateOfTransactionId\" IS DISTINCT FROM \"Id\"");
                        });
                });

            modelBuilder.Entity("Margen.Domain.Entities.AccessToken", b =>
                {
                    b.HasOne("Margen.Domain.Entities.Device", "Device")
                        .WithMany("Tokens")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");
                });

            modelBuilder.Entity("Margen.Domain.Entities.Alert", b =>
                {
                    b.HasOne("Margen.Domain.Entities.IncomingEmail", "IncomingEmail")
                        .WithMany()
                        .HasForeignKey("IncomingEmailId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Margen.Domain.Entities.RecurringPayment", "RecurringPayment")
                        .WithMany()
                        .HasForeignKey("RecurringPaymentId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Margen.Domain.Entities.Transaction", "Transaction")
                        .WithMany()
                        .HasForeignKey("TransactionId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("IncomingEmail");

                    b.Navigation("RecurringPayment");

                    b.Navigation("Transaction");
                });

            modelBuilder.Entity("Margen.Domain.Entities.CategoryBudget", b =>
                {
                    b.HasOne("Margen.Domain.Entities.BudgetPeriod", "BudgetPeriod")
                        .WithMany("CategoryBudgets")
                        .HasForeignKey("BudgetPeriodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Margen.Domain.Entities.Category", "Category")
                        .WithMany("Budgets")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BudgetPeriod");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Margen.Domain.Entities.DeviceChallenge", b =>
                {
                    b.HasOne("Margen.Domain.Entities.Device", "Device")
                        .WithMany("Challenges")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");
                });

            modelBuilder.Entity("Margen.Domain.Entities.MerchantRule", b =>
                {
                    b.HasOne("Margen.Domain.Entities.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Margen.Domain.Entities.RecurringPayment", b =>
                {
                    b.HasOne("Margen.Domain.Entities.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Margen.Domain.Entities.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Account");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Margen.Domain.Entities.StatementProfile", b =>
                {
                    b.HasOne("Margen.Domain.Entities.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("Margen.Domain.Entities.Transaction", b =>
                {
                    b.HasOne("Margen.Domain.Entities.Account", "Account")
                        .WithMany("Transactions")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Margen.Domain.Entities.Category", "Category")
                        .WithMany("Transactions")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Margen.Domain.Entities.Transaction", "DuplicateOfTransaction")
                        .WithMany()
                        .HasForeignKey("DuplicateOfTransactionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Margen.Domain.Entities.IncomingEmail", "IncomingEmail")
                        .WithMany("Transactions")
                        .HasForeignKey("IncomingEmailId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Margen.Domain.Entities.Transaction", "RefundsTransaction")
                        .WithMany()
                        .HasForeignKey("RefundsTransactionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Account");

                    b.Navigation("Category");

                    b.Navigation("DuplicateOfTransaction");

                    b.Navigation("IncomingEmail");

                    b.Navigation("RefundsTransaction");
                });

            modelBuilder.Entity("Margen.Domain.Entities.Account", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("Margen.Domain.Entities.BudgetPeriod", b =>
                {
                    b.Navigation("CategoryBudgets");
                });

            modelBuilder.Entity("Margen.Domain.Entities.Category", b =>
                {
                    b.Navigation("Budgets");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("Margen.Domain.Entities.Device", b =>
                {
                    b.Navigation("Challenges");

                    b.Navigation("Tokens");
                });

            modelBuilder.Entity("Margen.Domain.Entities.IncomingEmail", b =>
                {
                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
